[package]
name = "agel-boot"
version = "1.6.0"
edition = "2021"
rust-version = "1.88"
publish = false

[dependencies]
agel-kernel-abi = { path = "../../crates/agel-kernel-abi", default-features = false }

[features]
selftest = []
monitor-selftest = []
native-selftest = []
isolation-selftest = []
isolated-repl = ["isolation-selftest"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = false

[workspace]
