#!/bin/sh
# Record exactly what the seL4 backend was built from and what is claimed about
# it.
#
# `docs/microkernel-research.md` requires that "claims about formal assurance
# name the exact proved configuration and assumptions", and that a
# configuration outside the proofs "must be reported as an unverified
# configuration". This script is how that requirement is met mechanically: it
# prints the identity of every artifact and states plainly what the
# verification status of that combination is.
set -eu

board=${MICROKIT_BOARD:-qemu_virt_aarch64}
config=${MICROKIT_CONFIG:-release}
project_dir=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
build_dir="$project_dir/target/sel4"
sdk=${MICROKIT_SDK:-$build_dir/microkit-sdk-2.3.0}

if ! test -d "$sdk"; then
  printf '%s\n' "no SDK at $sdk; run ./scripts/build-sel4.sh first" >&2
  exit 1
fi

board_dir="$sdk/board/$board/$config"
kernel_config="$board_dir/include/kernel/gen_config.h"

digest() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    sha256sum "$1" | cut -d' ' -f1
  fi
}

kernel_option() {
  if grep -q "define $1" "$kernel_config" 2>/dev/null; then
    printf 'yes'
  else
    printf 'no'
  fi
}

printf '# Agel seL4 backend manifest\n\n'
printf 'Generated by `./scripts/sel4-manifest.sh`. Everything below is read from\n'
printf 'the artifacts that were actually built, not from documentation.\n\n'

printf '## Trusted base\n\n'
printf 'These come from the pinned SDK release and from this repository, so they\n'
printf 'are the same for everyone who builds this system. CI checks them.\n\n'
printf '| Artifact | SHA-256 |\n|---|---|\n'
printf '| Microkit SDK version | %s |\n' "$(cat "$sdk/VERSION")"
printf '| board / configuration | %s / %s |\n' "$board" "$config"
printf '| seL4 kernel (`sel4.elf`) | `%s` |\n' "$(digest "$board_dir/elf/sel4.elf")"
printf '| Microkit loader | `%s` |\n' "$(digest "$board_dir/elf/loader.elf")"
printf '| Microkit monitor | `%s` |\n' "$(digest "$board_dir/elf/monitor.elf")"
printf '| `libmicrokit.a` | `%s` |\n' "$(digest "$board_dir/lib/libmicrokit.a")"
printf '| System description | `%s` |\n' "$(digest "$project_dir/boot/microkit/agel.system")"

printf '\n## This build\n\n'
printf 'These depend on the compiler that produced them, so they identify one\n'
printf 'build rather than the system. CI does not check them; reproducing them\n'
printf 'requires the same toolchain.\n\n'
printf '| Artifact | SHA-256 |\n|---|---|\n'
printf '| Rust | `%s` |\n' "$(rustc --version)"
if test -f "$build_dir/agel-sel4.img"; then
  printf '| Bootable image | `%s` |\n' "$(digest "$build_dir/agel-sel4.img")"
fi
for domain in agel-serial agel-broker agel-recovery agel-world; do
  if test -f "$build_dir/domains/$domain.elf"; then
    printf '| Protection domain `%s` | `%s` |\n' \
      "${domain#agel-}" "$(digest "$build_dir/domains/$domain.elf")"
  fi
done
printf '\nProtection domains are built for `aarch64-unknown-none-softfloat`. The seL4\n'
printf 'kernel and `libmicrokit.a` are the published release binaries: nothing in\n'
printf 'this repository compiles, patches, or configures the kernel.\n'

printf '\n## Kernel configuration\n\n'
printf '| Option | Set |\n|---|---|\n'
printf '| `CONFIG_KERNEL_MCS` | %s |\n' "$(kernel_option CONFIG_KERNEL_MCS)"
printf '| `CONFIG_ARM_HYPERVISOR_SUPPORT` | %s |\n' \
  "$(kernel_option CONFIG_ARM_HYPERVISOR_SUPPORT)"
printf '| `CONFIG_ENABLE_SMP_SUPPORT` | %s |\n' "$(kernel_option CONFIG_ENABLE_SMP_SUPPORT)"
printf '| `CONFIG_DEBUG_BUILD` | %s |\n' "$(kernel_option CONFIG_DEBUG_BUILD)"
printf '| `CONFIG_PRINTING` | %s |\n' "$(kernel_option CONFIG_PRINTING)"

printf '\n## What is and is not verified\n\n'
printf 'The kernel binary above is an unmodified seL4 release. Agel adds no kernel\n'
printf 'objects, no syscalls, and no patches; the Agel contract is answered by an\n'
printf 'ordinary unprivileged server.\n\n'
if test "$(kernel_option CONFIG_KERNEL_MCS)" = yes; then
  printf '**This is not a verified configuration.** Every Microkit board ships an MCS\n'
  printf 'kernel, and seL4'"'"'s verified-configurations table lists MCS proofs as ongoing\n'
  printf 'rather than complete on every architecture'
  if test "$(kernel_option CONFIG_ARM_HYPERVISOR_SUPPORT)" = yes; then
    printf '; this board additionally enables\nhypervisor support, which is a further configuration outside the AArch64\nproofs'
  fi
  printf '. Running on an unmodified verified *kernel implementation* is not\n'
  printf 'the same as running a *verified configuration*, and this spike does the\n'
  printf 'former.\n\n'
fi
printf 'Nothing here is a claim about the correctness of the Agel code above the\n'
printf 'kernel. The system description grants the authority; the protection domains\n'
printf 'are ordinary Rust; neither has been verified by anyone.\n'
