[package]
name = "agel-supervisor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
agel-core = { path = "../agel-core" }
agel-image = { path = "../agel-image" }
agel-integrity = { path = "../agel-integrity" }

[lints]
workspace = true
